In [1]:
import pandas as pd

taxonomy = pd.read_csv("Train/train_taxonomy.tsv", sep="\t", names=["accession", "tax_id"])
taxonomy.head()

    accession  tax_id
0  A0A0C5B5G6    9606
1      A0JNW5    9606
2      A0JP26    9606
3      A0PK11    9606
4      A1A4S6    9606

In [2]:
import pandas as pd

# Read TSV file
train_terms = pd.read_csv('Train/train_terms.tsv', sep='\t')


# Display first few rows
train_terms.head()

  EntryID        term aspect
0  Q5W0B1  GO:0000785      C
1  Q5W0B1  GO:0004842      F
2  Q5W0B1  GO:0051865      P
3  Q5W0B1  GO:0006275      P
4  Q5W0B1  GO:0006513      P

In [3]:
import pronto

ontology = pronto.Ontology("Train/go-basic.obo")
data = []
# .terms is now a method, so call it with ()
for term in ontology.terms():
    data.append({
        "term_id": term.id,
        "term_name": term.name
    })
ontology = pd.DataFrame(data)
ontology.head()

      term_id                                          term_name
0  GO:0000001                          mitochondrion inheritance
1  GO:0000002                   mitochondrial genome maintenance
2  GO:0000003                              obsolete reproduction
3  GO:0000005              obsolete ribosomal chaperone activity
4  GO:0000006  high-affinity zinc transmembrane transporter a...

In [4]:
from Bio import SeqIO
import pandas as pd

# Read all sequences from FASTA file
sequences = []

for record in SeqIO.parse("Train/train_sequences.fasta", "fasta"):
    # Extract accession ID (middle part of sp|A0A0C5B5G6|MOTSC_HUMAN)
    accession = record.id.split('|')[1] if '|' in record.id else record.id
    
    # Extract protein name and organism
    entry_name = record.id.split('|')[2] if len(record.id.split('|')) > 2 else ''
    protein_name = entry_name.split('_')[0] if '_' in entry_name else entry_name
    organism = entry_name.split('_')[1] if '_' in entry_name else ''
    
    sequences.append({
        'accession': accession,
        'protein_name': protein_name,
        'organism': organism,
        'sequence': str(record.seq),
        'length': len(record.seq)
    })

# Convert to DataFrame
sequences_df = pd.DataFrame(sequences)

# Display first few rows
print(f"Total sequences: {len(sequences_df)}")
sequences_df.head()

Total sequences: 82404

,accession,protein_name,organism,sequence,length
0,A0A0C5B5G6,MOTSC,HUMAN,MRWQEMGYIFYPRKLR,16
1,A0JNW5,BLT3B,HUMAN,MAGIIKKQILKHLSRFTKNLSPDKINLSTLKGEGELKNLELDEEVL...,1464
2,A0JP26,POTB3,HUMAN,MVAEVCSMPAASAVKKPFDLRSKMGKWCHHRFPCCRGSGKSNMGTS...,581
3,A0PK11,CLRN2,HUMAN,MPGWFKKAWYGLASLLSFSSFILIIVALVVPHWLSGKILCQTGVDL...,232
4,A1A4S6,RHG10,HUMAN,MGLQPLEFSDCYLDSPWFRERIRAHEAELERTNKFIKELIKDGKNL...,786

# Check for overlap colunms 

#### taxonomy: 
    - accession_id 

#### train sequences
    - accession 

#### train terms 
    - Entry ID - can be mapped with accession
    - term (GO)

#### ontology 
    - term ID (GO) -> can be mapped with term in train terms

In [5]:
# Compare accession identifier in taxonomy, train sequences, train terms 

taxonomy_ids = set(taxonomy["accession"].unique())
sequences_ids = set(sequences_df["accession"].unique())
train_terms_ids = set(train_terms["EntryID"].unique())

In [6]:
missing_in_sequences_from_taxonomy = taxonomy_ids - sequences_ids
print(missing_in_sequences_from_taxonomy)

set()

In [7]:
missing_in_train_terms_from_taxonomy = taxonomy_ids - train_terms_ids
print(missing_in_train_terms_from_taxonomy)

set()

In [8]:
missing_in_taxonomy_from_seq = sequences_ids - taxonomy_ids
print(missing_in_taxonomy_from_seq)

set()

In [9]:
missing_in_taxonomy_from_train_terms = train_terms_ids - taxonomy_ids
print(missing_in_taxonomy_from_train_terms)

set()

In [10]:
missing_in_sequeces_from_train_terms = train_terms_ids - sequences_ids
print(missing_in_sequeces_from_train_terms)

set()

Since there is no conflict, can merge all four data into one dataframe using accession

In [11]:
merged_taxonomy_train_terms = pd.merge(taxonomy, train_terms, left_on="accession", right_on="EntryID", how='left')
merged_taxonomy_train_terms.head()

    accession  tax_id     EntryID        term aspect
0  A0A0C5B5G6    9606  A0A0C5B5G6  GO:0001649      P
1  A0A0C5B5G6    9606  A0A0C5B5G6  GO:0033687      P
2  A0A0C5B5G6    9606  A0A0C5B5G6  GO:0005615      C
3  A0A0C5B5G6    9606  A0A0C5B5G6  GO:0005634      C
4  A0A0C5B5G6    9606  A0A0C5B5G6  GO:0005739      C

In [12]:
merged_taxonomy_train_terms.isnull().values.any()

np.False_

In [13]:
merged_taxonomy_train_terms.isnull().sum()

accession    0
tax_id       0
EntryID      0
term         0
aspect       0
dtype: int64

In [14]:
merged_taxonomy_train_terms.drop(columns=["EntryID"], inplace=True)

In [15]:
merged_taxonomy_train_terms

         accession  tax_id        term aspect
0       A0A0C5B5G6    9606  GO:0001649      P
1       A0A0C5B5G6    9606  GO:0033687      P
2       A0A0C5B5G6    9606  GO:0005615      C
3       A0A0C5B5G6    9606  GO:0005634      C
4       A0A0C5B5G6    9606  GO:0005739      C
...            ...     ...         ...    ...
537022      Q9Y7Q3  284812  GO:0005634      C
537023      Q9Y7Q3  284812  GO:0005739      C
537024      Q9Y7Q3  284812  GO:0005829      C
537025      Q9Y816  284812  GO:0005737      C
537026      Q9Y816  284812  GO:0005783      C

[537027 rows x 4 columns]

In [16]:
merged_train_seq = pd.merge(merged_taxonomy_train_terms, sequences_df, on="accession", how="left") 
merged_train_seq

,accession,tax_id,term,aspect,protein_name,organism,sequence,length
0,A0A0C5B5G6,9606,GO:0001649,P,MOTSC,HUMAN,MRWQEMGYIFYPRKLR,16
1,A0A0C5B5G6,9606,GO:0033687,P,MOTSC,HUMAN,MRWQEMGYIFYPRKLR,16
2,A0A0C5B5G6,9606,GO:0005615,C,MOTSC,HUMAN,MRWQEMGYIFYPRKLR,16
3,A0A0C5B5G6,9606,GO:0005634,C,MOTSC,HUMAN,MRWQEMGYIFYPRKLR,16
4,A0A0C5B5G6,9606,GO:0005739,C,MOTSC,HUMAN,MRWQEMGYIFYPRKLR,16
...,...,...,...,...,...,...,...,...
537022,Q9Y7Q3,284812,GO:0005634,C,YQ6A,SCHPO,MHSSRRKYNDMWTARLLIRSDQKEEKYPSFKKNAGKAINAHLIPKL...,149
537023,Q9Y7Q3,284812,GO:0005739,C,YQ6A,SCHPO,MHSSRRKYNDMWTARLLIRSDQKEEKYPSFKKNAGKAINAHLIPKL...,149
537024,Q9Y7Q3,284812,GO:0005829,C,YQ6A,SCHPO,MHSSRRKYNDMWTARLLIRSDQKEEKYPSFKKNAGKAINAHLIPKL...,149
537025,Q9Y816,284812,GO:0005737,C,YOND,SCHPO,MITEFIKSFLLFFFLPFFLSMPMIFATLGEFTDDQTHHYSTLPSCD...,142
537026,Q9Y816,284812,GO:0005783,C,YOND,SCHPO,MITEFIKSFLLFFFLPFFLSMPMIFATLGEFTDDQTHHYSTLPSCD...,142

In [17]:
merged_train_seq.isnull().values.any()

np.False_

In [18]:
merged_taxonomy_train_terms.isnull().sum()

accession    0
tax_id       0
term         0
aspect       0
dtype: int64

In [19]:
# Compare term identifier for ontology and merged_taxonomy_train_terms

taxonomy_terms_id = set(merged_train_seq['term'].unique())
ontology_id = set(ontology['term_id'].unique())

print(taxonomy_terms_id - ontology_id)
print(ontology_id - taxonomy_terms_id)

set()

In [20]:
go_not_taxonomy = ontology_id - taxonomy_terms_id
differences = len(go_not_taxonomy)
print(differences)

21976

There are `21,976` go terms that are not included in the train taxonomy

In [21]:
merged_taxonomy_train_terms.to_csv("merged_taxonomy_train_terms.csv", index=False)

finding: all entry id and accession id are matched

In [22]:
# Couting if there is multiple EntryID -> has many GO: Terms

count_multi = merged_train_seq.groupby("accession")['term'].count().reset_index(name='go_term_count')
multi_go = count_multi[count_multi["go_term_count"] > 1]

multi_go

        accession  go_term_count
5      A0A023FFD0              2
9      A0A023I7E1              2
12     A0A024RBG1              2
14     A0A026W182              7
15     A0A044RE18              3
...           ...            ...
82399      X2JI34              2
82400      X4Y2L4              2
82401      X5JA13              8
82402      X5JB51              8
82403      X5M5N0              8

[67167 rows x 2 columns]

In [23]:
!pip install tabulate

Requirement already satisfied: tabulate in c:\users\najaa\desktop\cafa 6\cafa-6-protein-function-prediction\py312-bio\lib\site-packages (0.9.0)

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
from tabulate import tabulate

organism_counts = (
    merged_train_seq['organism']
    .value_counts()
    .reset_index()
    .rename(columns={'index': 'Organism', 'organism': 'Count'})
)

print(tabulate(organism_counts, headers='keys', tablefmt='psql'))

+------+---------+---------+
|      | Count   |   count |
|------+---------+---------|
|    0 | HUMAN   |  155400 |
|    1 | MOUSE   |  109671 |
|    2 | ARATH   |   57405 |
|    3 | RAT     |   43418 |
|    4 | YEAST   |   37056 |
|    5 | DROME   |   28050 |
|    6 | SCHPO   |   20089 |
|    7 | CAEEL   |   14984 |
|    8 | ECOLI   |   14808 |
|    9 | DICDI   |    7301 |
|   10 | DANRE   |    6710 |
|   11 | MYCTU   |    4769 |
|   12 | CANAL   |    3304 |
|   13 | ORYSJ   |    3189 |
|   14 | CHICK   |    2594 |
|   15 | BOVIN   |    2587 |
|   16 | XENLA   |    2445 |
|   17 | PSEAE   |    1136 |
|   18 | EMENI   |     980 |
|   19 | BACSU   |     845 |
|   20 | PIG     |     833 |
|   21 | PLAF7   |     717 |
|   22 | RABIT   |     680 |
|   23 | MAIZE   |     670 |
|   24 | ASPFU   |     456 |
|   25 | CANLF   |     437 |
|   26 | TRYB2   |     406 |
|   27 | CHLRE   |     364 |
|   28 | SALTY   |     345 |
|   29 | SOLLC   |     320 |
|   30 | GIAIC   |     296 |
|   31 | ONCMY   |     285 |
|   32 | CANGA   |     273 |
|   33 | TRYBB   |     266 |
|   34 | ORYSI   |     241 |
|   35 | MEDTR   |     237 |
|   36 | SOYBN   |     189 |
|   37 | CRIGR   |     187 |
|   38 | PETHY   |     175 |
|   39 | XENTR   |     168 |
|   40 | CRYNH   |     158 |
|   41 | METJA   |     156 |
|   42 | ASPOR   |     143 |
|   43 | TOBAC   |     140 |
|   44 | PEA     |     137 |
|   45 | ANOGA   |     137 |
|   46 | LOTJA   |     120 |
|   47 | BOMMO   |     116 |
|   48 | STRPN   |     115 |
|   49 | ENTH1   |     114 |
|   50 | SHEEP   |     105 |
|   51 | ASPNC   |      99 |
|   52 | PLABA   |      98 |
|   53 | HELPY   |      95 |
|   54 | CAVPO   |      93 |
|   55 | CATRO   |      91 |
|   56 | PSEPK   |      83 |
|   57 | ORYSA   |      83 |
|   58 | ORYNI   |      80 |
|   59 | TETTS   |      77 |
|   60 | SPIOL   |      77 |
|   61 | STAA8   |      75 |
|   62 | NEUCR   |      75 |
|   63 | PANGI   |      74 |
|   64 | TOXGO   |      73 |
|   65 | SOLTU   |      71 |
|   66 | MESAU   |      66 |
|   67 | ASPNG   |      64 |
|   68 | PICSI   |      64 |
|   69 | MACFA   |      64 |
|   70 | ASPPU   |      64 |
|   71 | GOSHI   |      62 |
|   72 | APIME   |      61 |
|   73 | CHATD   |      59 |
|   74 | CANAX   |      57 |
|   75 | MACMU   |      56 |
|   76 | PAPSO   |      54 |
|   77 | ANGJA   |      54 |
|   78 | PENEN   |      54 |
|   79 | YEASX   |      54 |
|   80 | AEDAE   |      53 |
|   81 | SAPOF   |      52 |
|   82 | SCHMA   |      51 |
|   83 | CAPAN   |      49 |
|   84 | LEIMA   |      49 |
|   85 | ASCSU   |      48 |
|   86 | MELGA   |      48 |
|   87 | PYRO7   |      47 |
|   88 | WHEAT   |      46 |
|   89 | PINBN   |      45 |
|   90 | PINCO   |      44 |
|   91 | ICTPU   |      44 |
|   92 | SYLSP   |      44 |
|   93 | SALSA   |      42 |
|   94 | LOPWI   |      42 |
|   95 | HORSE   |      41 |
|   96 | HORVU   |      41 |
|   97 | MANSE   |      40 |
|   98 | SINHE   |      40 |
|   99 | TITOB   |      39 |
|  100 | GIBZE   |      39 |
|  101 | ASCTR   |      38 |
|  102 | TACTR   |      38 |
|  103 | LITSE   |      37 |
|  104 | CAPHI   |      37 |
|  105 | ORYLA   |      36 |
|  106 | ASPTE   |      36 |
|  107 | TAEGU   |      36 |
|  108 | MALDO   |      36 |
|  109 | PENBR   |      36 |
|  110 | IPOBA   |      35 |
|  111 | PHYPA   |      34 |
|  112 | SCHKA   |      34 |
|  113 | GALME   |      34 |
|  114 | SCHPM   |      32 |
|  115 | ISORU   |      31 |
|  116 | ODOIS   |      31 |
|  117 | ANTMA   |      31 |
|  118 | HUMLU   |      31 |
|  119 | RANTE   |      30 |
|  120 | VITVI   |      30 |
|  121 | SOLHA   |      30 |
|  122 | PLAFO   |      29 |
|  123 | LITRO   |      29 |
|  124 | GLOMM   |      29 |
|  125 | PLAFX   |      29 |
|  126 | RICCO   |      28 |
|  127 | CARIP   |      28 |
|  128 | ACTCC   |      28 |
|  129 | IXORI   |      28 |
|  130 | EUGGR   |      27 |
|  131 | KOMPG   |      27 |
|  132 | ODOGR   |      27 |
|  133 | PLAVS   |      27 |
|  134 | POPTR   |      27 |
|  135 | COTJA   |      26 |
|  136 | ASPN1   |      26 |
|  137 | PICPA   |      25 |
|  138 | PINTA   |      25 |
|  139 | LIMKU   |      25 |
|  140 | RANDH   |      25 |
|  141 | PIGEN   |      25 |
|  142 | STRPU   |      25 |
|  143 | MYCMD   |      25 |
|  144 | SORBI   |      24 |
|  145 | MICSU   |      24 |
|  146 | APLCA   |      24 |
|  147 | SALT1   |      24 |
|  148 | CRUCA   |      24 |
|  149 | OLIMR   |      24 |
|  150 | PUNGR   |      24 |
|  151 | MUSAC   |      24 |
|  152 | PICGL   |      23 |
|  153 | NICBE   |      23 |
|  154 | PARPY   |      23 |
|  155 | ARTAN   |      23 |
|  156 | PELLE   |      23 |
|  157 | PIPNI   |      23 |
|  158 | BOTMA   |      23 |
|  159 | HYPJE   |      22 |
|  160 | CRODM   |      22 |
|  161 | LITPE   |      22 |
|  162 | CHLAE   |      21 |
|  163 | MANRB   |      21 |
|  164 | BOMVA   |      21 |
|  165 | RANDY   |      21 |
|  166 | PLAFA   |      21 |
|  167 | SESIN   |      21 |
|  168 | ONCKE   |      20 |
|  169 | PELRI   |      20 |
|  170 | ORIVU   |      20 |
|  171 | LAVPL   |      20 |
|  172 | CRYNJ   |      20 |
|  173 | POLPI   |      20 |
|  174 | HELAN   |      20 |
|  175 | RAUSE   |      20 |
|  176 | PENAE   |      20 |
|  177 | LAVST   |      20 |
|  178 | TOXGM   |      20 |
|  179 | BRANA   |      20 |
|  180 | LAVVI   |      20 |
|  181 | STRNX   |      19 |
|  182 | AQUCT   |      19 |
|  183 | TOXGG   |      19 |
|  184 | CROAT   |      19 |
|  185 | LITPA   |      19 |
|  186 | MENPI   |      19 |
|  187 | GIAIN   |      19 |
|  188 | HYAOR   |      18 |
|  189 | MARPO   |      18 |
|  190 | BACCR   |      18 |
|  191 | LINUS   |      18 |
|  192 | BARVU   |      18 |
|  193 | BRADI   |      18 |
|  194 | THUPL   |      18 |
|  195 | OPHHA   |      17 |
|  196 | ANDAU   |      17 |
|  197 | RHIO9   |      17 |
|  198 | PENVA   |      17 |
|  199 | ASPFM   |      17 |
|  200 | DERPT   |      17 |
|  201 | LITFA   |      17 |
|  202 | BYSSP   |      16 |
|  203 | PSEEC   |      16 |
|  204 | BOMIG   |      16 |
|  205 | TRIFG   |      16 |
|  206 | KLULA   |      16 |
|  207 | PICXS   |      16 |
|  208 | MARBU   |      16 |
|  209 | HAECO   |      16 |
|  210 | PICAN   |      16 |
|  211 | CRAVI   |      16 |
|  212 | PHYDL   |      16 |
|  213 | PLAAC   |      16 |
|  214 | BOTLC   |      16 |
|  215 | SPAPA   |      16 |
|  216 | TRYCC   |      16 |
|  217 | PHYIT   |      16 |
|  218 | SECCE   |      16 |
|  219 | ALSSC   |      15 |
|  220 | BOTAT   |      15 |
|  221 | ALLSA   |      15 |
|  222 | LACMU   |      15 |
|  223 | GIBM7   |      15 |
|  224 | PHATC   |      15 |
|  225 | CAVCU   |      15 |
|  226 | CUCME   |      15 |
|  227 | APICE   |      15 |
|  228 | HESAR   |      15 |
|  229 | CENBA   |      15 |
|  230 | PHONI   |      15 |
|  231 | CRISI   |      15 |
|  232 | BOTJA   |      15 |
|  233 | HEDCO   |      15 |
|  234 | CANSA   |      15 |
|  235 | TALVA   |      15 |
|  236 | MICUN   |      15 |
|  237 | MALPA   |      14 |
|  238 | TANCI   |      14 |
|  239 | NIDOK   |      14 |
|  240 | PANCL   |      14 |
|  241 | PATPE   |      14 |
|  242 | ASPFN   |      14 |
|  243 | PENMO   |      14 |
|  244 | ZYMTI   |      14 |
|  245 | NIGSA   |      14 |
|  246 | ECHOC   |      14 |
|  247 | HYDVU   |      14 |
|  248 | STYPI   |      14 |
|  249 | ODOJI   |      14 |
|  250 | HALAI   |      14 |
|  251 | LATSA   |      14 |
|  252 | BRUMA   |      13 |
|  253 | CRYJA   |      13 |
|  254 | VIPAA   |      13 |
|  255 | TANPA   |      13 |
|  256 | CUCSA   |      13 |
|  257 | ACTDE   |      13 |
|  258 | PRUDU   |      13 |
|  259 | MORAL   |      13 |
|  260 | MACLB   |      13 |
|  261 | BLAAD   |      13 |
|  262 | COLHI   |      13 |
|  263 | SELML   |      13 |
|  264 | LACTA   |      13 |
|  265 | PHAVU   |      13 |
|  266 | STRYX   |      13 |
|  267 | COCNU   |      13 |
|  268 | SALMI   |      13 |
|  269 | YARLI   |      13 |
|  270 | RHOPR   |      13 |
|  271 | PENCH   |      13 |
|  272 | CRAPL   |      13 |
|  273 | TAROF   |      13 |
|  274 | CAEBR   |      13 |
|  275 | LEIDO   |      13 |
|  276 | AJECA   |      13 |
|  277 | POGCB   |      12 |
|  278 | NEOS2   |      12 |
|  279 | GLYEC   |      12 |
|  280 | EMEND   |      12 |
|  281 | ALOAR   |      12 |
|  282 | PHYSA   |      12 |
|  283 | HYDCO   |      12 |
|  284 | TRICA   |      12 |
|  285 | AQUCR   |      12 |
|  286 | DIOPO   |      12 |
|  287 | OCTVU   |      12 |
|  288 | CERMR   |      12 |
|  289 | SCOSC   |      12 |
|  290 | ECHES   |      12 |
|  291 | NEMVE   |      12 |
|  292 | CRIRI   |      12 |
|  293 | ISOMC   |      12 |
|  294 | VITRO   |      12 |
|  295 | FUSO4   |      12 |
|  296 | AMOJI   |      12 |
|  297 | PAGMA   |      12 |
|  298 | CAMHI   |      12 |
|  299 | CENOR   |      12 |
|  300 | NEZVI   |      12 |
|  301 | MEDSA   |      12 |
|  302 | PSEAI   |      12 |
|  303 | BUNCI   |      12 |
|  304 | GOSBA   |      12 |
|  305 | ISOER   |      12 |
|  306 | TITMA   |      12 |
|  307 | VERDV   |      12 |
|  308 | BOARA   |      11 |
|  309 | ASPC5   |      11 |
|  310 | GLOTR   |      11 |
|  311 | PHALU   |      11 |
|  312 | THYVU   |      11 |
|  313 | DIOJA   |      11 |
|  314 | ASPTN   |      11 |
|  315 | ONCTS   |      11 |
|  316 | RHISA   |      11 |
|  317 | PARTE   |      11 |
|  318 | ARAHY   |      11 |
|  319 | CRIFA   |      11 |
|  320 | PENPX   |      11 |
|  321 | CORAV   |      11 |
|  322 | BUTOC   |      11 |
|  323 | SORAU   |      11 |
|  324 | PIRLC   |      11 |
|  325 | LUPLU   |      11 |
|  326 | PLAFK   |      11 |
|  327 | CANBO   |      11 |
|  328 | LEITA   |      11 |
|  329 | CONAO   |      11 |
|  330 | OCIBA   |      10 |
|  331 | PETMA   |      10 |
|  332 | BOMOR   |      10 |
|  333 | LITCU   |      10 |
|  334 | PALPR   |      10 |
|  335 | PNECA   |      10 |
|  336 | CARAU   |      10 |
|  337 | LUPAN   |      10 |
|  338 | VITAC   |      10 |
|  339 | PHACH   |      10 |
|  340 | STENO   |      10 |
|  341 | NAJKA   |      10 |
|  342 | NICSU   |      10 |
|  343 | PSETE   |      10 |
|  344 | HOLDI   |      10 |
|  345 | ORADR   |      10 |
|  346 | KALDA   |      10 |
|  347 | ONCVO   |      10 |
|  348 | NEOFS   |      10 |
|  349 | OXYSU   |      10 |
|  350 | NICGL   |      10 |
|  351 | TETBN   |      10 |
|  352 | LEIME   |      10 |
|  353 | JUGRE   |      10 |
|  354 | ARMME   |      10 |
|  355 | KITPR   |      10 |
|  356 | HEVBR   |      10 |
|  357 | MYCGE   |      10 |
|  358 | BITAR   |      10 |
|  359 | PLOIN   |      10 |
|  360 | GINBI   |      10 |
|  361 | LITPI   |      10 |
|  362 | COFAR   |      10 |
|  363 | ECOBW   |      10 |
|  364 | PROEL   |      10 |
|  365 | PENBI   |      10 |
|  366 | COTCO   |      10 |
|  367 | MYTTR   |      10 |
|  368 | STERE   |      10 |
|  369 | BUBBU   |      10 |
|  370 | PSEPY   |      10 |
|  371 | FORIN   |       9 |
|  372 | CALSE   |       9 |
|  373 | AYTFU   |       9 |
|  374 | XYLAI   |       9 |
|  375 | CONSP   |       9 |
|  376 | PERFR   |       9 |
|  377 | CASCR   |       9 |
|  378 | CROPO   |       9 |
|  379 | IXOSC   |       9 |
|  380 | SALFT   |       9 |
|  381 | MACRS   |       9 |
|  382 | DIPMA   |       9 |
|  383 | NICLA   |       9 |
|  384 | RANJA   |       9 |
|  385 | BOTFU   |       9 |
|  386 | LOXIN   |       9 |
|  387 | COCCA   |       9 |
|  388 | PSEUR   |       9 |
|  389 | TRIIF   |       9 |
|  390 | MUSPF   |       9 |
|  391 | SALPM   |       9 |
|  392 | RUDPH   |       9 |
|  393 | ESCCA   |       9 |
|  394 | NOSB1   |       9 |
|  395 | ANAPL   |       9 |
|  396 | POPAL   |       9 |
|  397 | PELSA   |       9 |
|  398 | DIACA   |       9 |
|  399 | NICAT   |       9 |
|  400 | REBSA   |       9 |
|  401 | RANAR   |       9 |
|  402 | PENRF   |       9 |
|  403 | CALOF   |       9 |
|  404 | SALOF   |       9 |
|  405 | CRYAT   |       9 |
|  406 | NARPS   |       9 |
|  407 | APLDA   |       9 |
|  408 | STACH   |       9 |
|  409 | HETMG   |       8 |
|  410 | ERYQU   |       8 |
|  411 | PAROL   |       8 |
|  412 | CALJA   |       8 |
|  413 | PSICU   |       8 |
|  414 | CHISP   |       8 |
|  415 | TOXGV   |       8 |
|  416 | PSEAM   |       8 |
|  417 | TOOSI   |       8 |
|  418 | ARGME   |       8 |
|  419 | ZINEL   |       8 |
|  420 | AGADC   |       8 |
|  421 | HOTJU   |       8 |
|  422 | LEUCN   |       8 |
|  423 | CHAFM   |       8 |
|  424 | CYCAE   |       8 |
|  425 | CARIL   |       8 |
|  426 | CONPU   |       8 |
|  427 | CRYD2   |       8 |
|  428 | NICPL   |       8 |
|  429 | PASSA   |       8 |
|  430 | CURLO   |       8 |
|  431 | DIOKA   |       8 |
|  432 | AJURE   |       8 |
|  433 | TRIPP   |       8 |
|  434 | CENMA   |       8 |
|  435 | CRILO   |       8 |
|  436 | DABRR   |       8 |
|  437 | TRYCR   |       8 |
|  438 | PETCR   |       8 |
|  439 | CAMAC   |       8 |
|  440 | HARSA   |       8 |
|  441 | PROJR   |       8 |
|  442 | PARVI   |       8 |
|  443 | CENTE   |       8 |
|  444 | PSEPD   |       8 |
|  445 | CHRAE   |       8 |
|  446 | BETPL   |       8 |
|  447 | HIPPR   |       8 |
|  448 | FLATR   |       8 |
|  449 | TAXCU   |       8 |
|  450 | ORNAN   |       8 |
|  451 | PODAS   |       8 |
|  452 | CERFI   |       8 |
|  453 | SCHOC   |       8 |
|  454 | FELCA   |       8 |
|  455 | PSEMU   |       8 |
|  456 | RHODA   |       7 |
|  457 | PLEOS   |       7 |
|  458 | MUSDO   |       7 |
|  459 | ASPCL   |       7 |
|  460 | AGACL   |       7 |
|  461 | MAGGA   |       7 |
|  462 | PHYAM   |       7 |
|  463 | VANPL   |       7 |
|  464 | HAPCH   |       7 |
|  465 | OSTTA   |       7 |
|  466 | SANAL   |       7 |
|  467 | NICAL   |       7 |
|  468 | LINAL   |       7 |
|  469 | PRUPE   |       7 |
|  470 | SCYSE   |       7 |
|  471 | BRAFL   |       7 |
|  472 | AGKCL   |       7 |
|  473 | LUTAY   |       7 |
|  474 | CAERE   |       7 |
|  475 | PHYDI   |       7 |
|  476 | PHLDU   |       7 |
|  477 | MANES   |       7 |
|  478 | CONGI   |       7 |
|  479 | BOTFB   |       7 |
|  480 | OOCBI   |       7 |
|  481 | OLEEU   |       7 |
|  482 | BOIIR   |       7 |
|  483 | CANPC   |       7 |
|  484 | LUMTE   |       7 |
|  485 | FRIUN   |       7 |
|  486 | AMBCJ   |       7 |
|  487 | STRCA   |       7 |
|  488 | HYPEX   |       7 |
|  489 | NICSY   |       7 |
|  490 | SALSC   |       7 |
|  491 | MARVU   |       7 |
|  492 | LINCY   |       7 |
|  493 | PHYNA   |       7 |
|  494 | AVESA   |       7 |
|  495 | FAGES   |       7 |
|  496 | CONLT   |       7 |
|  497 | BIOGL   |       7 |
|  498 | PARBA   |       7 |
|  499 | GOSAR   |       7 |
|  500 | LINPE   |       7 |
|  501 | RHIMP   |       7 |
|  502 | CITLI   |       7 |
|  503 | SCHAM   |       6 |
|  504 | ONCFA   |       6 |
|  505 | BASAL   |       6 |
|  506 | ACRHI   |       6 |
|  507 | BANDI   |       6 |
|  508 | EUSSE   |       6 |
|  509 | MOMCO   |       6 |
|  510 | CHOCI   |       6 |
|  511 | CANEN   |       6 |
|  512 | HETMC   |       6 |
|  513 | MURHI   |       6 |
|  514 | PIMDI   |       6 |
|  515 | SEPOF   |       6 |
|  516 | ODODO   |       6 |
|  517 | CARMA   |       6 |
|  518 | UNIPI   |       6 |
|  519 | SYNTU   |       6 |
|  520 | DABSI   |       6 |
|  521 | COLLN   |       6 |
|  522 | CYRAL   |       6 |
|  523 | CERUI   |       6 |
|  524 | NOTSC   |       6 |
|  525 | PSEAB   |       6 |
|  526 | THRSP   |       6 |
|  527 | GLOHA   |       6 |
|  528 | RHODL   |       6 |
|  529 | TRYBR   |       6 |
|  530 | ELEED   |       6 |
|  531 | LILDA   |       6 |
|  532 | HYPAN   |       6 |
|  533 | RHOJU   |       6 |
|  534 | ACAGO   |       6 |
|  535 | IPSPI   |       6 |
|  536 | LYCMC   |       6 |
|  537 | TALMA   |       6 |
|  538 | MOROL   |       6 |
|  539 | GRISQ   |       6 |
|  540 | CLAPU   |       6 |
|  541 | PHARH   |       6 |
|  542 | HELLU   |       6 |
|  543 | CHITE   |       6 |
|  544 | GENTR   |       6 |
|  545 | MUCCL   |       6 |
|  546 | ACASS   |       6 |
|  547 | DEIAC   |       6 |
|  548 | BOMTE   |       6 |
|  549 | CANAR   |       6 |
|  550 | BRARP   |       6 |
|  551 | HYPJR   |       6 |
|  552 | ANUPH   |       6 |
|  553 | CRODU   |       6 |
|  554 | TALFU   |       6 |
|  555 | CRYCV   |       6 |
|  556 | SELSX   |       6 |
|  557 | PENRW   |       6 |
|  558 | MYCSO   |       6 |
|  559 | BOTAL   |       6 |
|  560 | TAESO   |       6 |
|  561 | ANGAN   |       6 |
|  562 | HALRU   |       6 |
|  563 | ASPKW   |       6 |
|  564 | OREDC   |       6 |
|  565 | EPICO   |       6 |
|  566 | CROHD   |       6 |
|  567 | MACFV   |       6 |
|  568 | HAELO   |       6 |
|  569 | BOTBA   |       6 |
|  570 | DROHY   |       6 |
|  571 | PAROT   |       6 |
|  572 | NAJHH   |       6 |
|  573 | ABRPR   |       6 |
|  574 | TAKRU   |       6 |
|  575 | EISFE   |       6 |
|  576 | EUGLO   |       6 |
|  577 | BOTBR   |       6 |
|  578 | LAVAN   |       6 |
|  579 | NICGU   |       6 |
|  580 | TAXCA   |       6 |
|  581 | BOMMX   |       6 |
|  582 | CICIN   |       6 |
|  583 | BISBB   |       6 |
|  584 | ALEAU   |       6 |
|  585 | DROEU   |       6 |
|  586 | APLKU   |       6 |
|  587 | ASPAW   |       6 |
|  588 | LUPAL   |       6 |
|  589 | THRSX   |       6 |
|  590 | TRIGS   |       6 |
|  591 | HYAAR   |       6 |
|  592 | CYPCA   |       6 |
|  593 | KALSE   |       6 |
|  594 | HYDVD   |       6 |
|  595 | ALTAL   |       6 |
|  596 | AVIMR   |       6 |
|  597 | PETIN   |       6 |
|  598 | SOLPI   |       6 |
|  599 | CANTR   |       6 |
|  600 | PENRU   |       6 |
|  601 | VIGRR   |       6 |
|  602 | CIMLE   |       6 |
|  603 | PARCM   |       6 |
|  604 | PYRAP   |       6 |
|  605 | SIRGR   |       5 |
|  606 | SPOFR   |       5 |
|  607 | PICAB   |       5 |
|  608 | SARPE   |       5 |
|  609 | PHYBI   |       5 |
|  610 | SAGOE   |       5 |
|  611 | ACTRA   |       5 |
|  612 | OVOOK   |       5 |
|  613 | EIMTE   |       5 |
|  614 | BRABE   |       5 |
|  615 | MELAF   |       5 |
|  616 | ENCCU   |       5 |
|  617 | NESMA   |       5 |
|  618 | TENMO   |       5 |
|  619 | PROFL   |       5 |
|  620 | VIGUS   |       5 |
|  621 | HALPP   |       5 |
|  622 | PYRCO   |       5 |
|  623 | RADCR   |       5 |
|  624 | CANCT   |       5 |
|  625 | INUHU   |       5 |
|  626 | DAVTA   |       5 |
|  627 | MACLN   |       5 |
|  628 | CANGB   |       5 |
|  629 | HORVV   |       5 |
|  630 | SALSN   |       5 |
|  631 | SOLIN   |       5 |
|  632 | TYRPU   |       5 |
|  633 | CITSI   |       5 |
|  634 | VIPAP   |       5 |
|  635 | TITDI   |       5 |
|  636 | APOSC   |       5 |
|  637 | LIMPO   |       5 |
|  638 | DAUCA   |       5 |
|  639 | VANHU   |       5 |
|  640 | OXYTA   |       5 |
|  641 | OSCPE   |       5 |
|  642 | FUSFU   |       5 |
|  643 | COPCI   |       5 |
|  644 | CANPA   |       5 |
|  645 | TAXCH   |       5 |
|  646 | PHYIN   |       5 |
|  647 | SABMA   |       5 |
|  648 | PODAN   |       5 |
|  649 | MICMP   |       5 |
|  650 | TRIRC   |       5 |
|  651 | MACIN   |       5 |
|  652 | PIREQ   |       5 |
|  653 | MILFA   |       5 |
|  654 | OVOMO   |       5 |
|  655 | PERFH   |       5 |
|  656 | YEASC   |       5 |
|  657 | PINKO   |       5 |
|  658 | METAQ   |       5 |
|  659 | PENCI   |       5 |
|  660 | PSESM   |       5 |
|  661 | HALRO   |       5 |
|  662 | PENSQ   |       5 |
|  663 | GLOUS   |       5 |
|  664 | ZIZMA   |       5 |
|  665 | TETTH   |       5 |
|  666 | LUCCU   |       5 |
|  667 | BRAOT   |       5 |
|  668 | BRAOB   |       5 |
|  669 | BLOTA   |       5 |
|  670 | LYCCL   |       5 |
|  671 | MORAP   |       5 |
|  672 | DROVI   |       5 |
|  673 | LENCU   |       5 |
|  674 | PSEAW   |       5 |
|  675 | CYPE1   |       5 |
|  676 | DROSI   |       5 |
|  677 | ACULO   |       5 |
|  678 | ANISI   |       5 |
|  679 | IXOSI   |       5 |
|  680 | PODCO   |       5 |
|  681 | ORTSC   |       5 |
|  682 | AMICA   |       5 |
|  683 | CASCN   |       5 |
|  684 | MYRPI   |       5 |
|  685 | PERAE   |       5 |

In [25]:
merged_train_seq.head()

,accession,tax_id,term,aspect,protein_name,organism,sequence,length
0,A0A0C5B5G6,9606,GO:0001649,P,MOTSC,HUMAN,MRWQEMGYIFYPRKLR,16
1,A0A0C5B5G6,9606,GO:0033687,P,MOTSC,HUMAN,MRWQEMGYIFYPRKLR,16
2,A0A0C5B5G6,9606,GO:0005615,C,MOTSC,HUMAN,MRWQEMGYIFYPRKLR,16
3,A0A0C5B5G6,9606,GO:0005634,C,MOTSC,HUMAN,MRWQEMGYIFYPRKLR,16
4,A0A0C5B5G6,9606,GO:0005739,C,MOTSC,HUMAN,MRWQEMGYIFYPRKLR,16

67k+ data has multiple protein functionality (go:term)

In [26]:
merged_train_seq.to_csv("merged_final_seq.csv", index=False)

### Load the test data

In [27]:
print("\n Loading Test Data")

test_sequences = []

for record in SeqIO.parse("Test/testsuperset.fasta", "fasta"):
    parts = record.description.split()
    accession = parts[0]
    tax_id = parts[1] if len(parts) > 1 else ''

    test_sequences.append({
        'accession' : accession, 
        'tax_id' : int(tax_id),
        'sequence' : str(record.seq),
        'length' : len(record.seq)
    })

df_test_fasta = pd.DataFrame(test_sequences)
print(f"Loaded {len(df_test_fasta)} test fasta data")

 Loading Test Data
Loaded 224309 test fasta data

In [28]:
df_test_fasta.head()

,accession,tax_id,sequence,length
0,A0A0C5B5G6,9606,MRWQEMGYIFYPRKLR,16
1,A0A1B0GTW7,9606,MLLLLLLLLLLPPLVLRVAASRCLHDETQKSVSLLRPPFSQLPSKS...,788
2,A0JNW5,9606,MAGIIKKQILKHLSRFTKNLSPDKINLSTLKGEGELKNLELDEEVL...,1464
3,A0JP26,9606,MVAEVCSMPAASAVKKPFDLRSKMGKWCHHRFPCCRGSGKSNMGTS...,581
4,A0PK11,9606,MPGWFKKAWYGLASLLSFSSFILIIVALVVPHWLSGKILCQTGVDL...,232

In [29]:
df_test_tsv = pd.read_csv('Test/testsuperset-taxon-list.tsv', sep='\t')
df_test_tsv.head()

      ID                       Species
0   9606                  Homo sapiens
1  10116             Rattus norvegicus
2  39947  Oryza sativa subsp. japonica
3   7955                   Danio rerio
4   7227       Drosophila melanogaster

In [30]:
df_test = pd.merge(df_test_tsv, df_test_fasta, left_on="ID", right_on="tax_id", how="left")
df_test.head()

,ID,Species,accession,tax_id,sequence,length
0,9606,Homo sapiens,A0A0C5B5G6,9606,MRWQEMGYIFYPRKLR,16
1,9606,Homo sapiens,A0A1B0GTW7,9606,MLLLLLLLLLLPPLVLRVAASRCLHDETQKSVSLLRPPFSQLPSKS...,788
2,9606,Homo sapiens,A0JNW5,9606,MAGIIKKQILKHLSRFTKNLSPDKINLSTLKGEGELKNLELDEEVL...,1464
3,9606,Homo sapiens,A0JP26,9606,MVAEVCSMPAASAVKKPFDLRSKMGKWCHHRFPCCRGSGKSNMGTS...,581
4,9606,Homo sapiens,A0PK11,9606,MPGWFKKAWYGLASLLSFSSFILIIVALVVPHWLSGKILCQTGVDL...,232

In [31]:
print(df_test['ID'].isna().sum())
print(df_test['tax_id'].isna().sum())

0
0

In [32]:
from tabulate import tabulate

species_counts = (
    df_test['Species']
    .value_counts()
    .reset_index()
    .rename(columns={'index': 'Species', 'organism': 'Count'})
)

print(tabulate(species_counts, headers='keys', tablefmt='psql'))

+------+-----------------------------------------------------------------------------------------------------------------------------------------+---------+
|      | Species                                                                                                                                 |   count |
|------+-----------------------------------------------------------------------------------------------------------------------------------------+---------|
|    0 | Homo sapiens                                                                                                                            |   20420 |
|    1 | Mus musculus                                                                                                                            |   17240 |
|    2 | Arabidopsis thaliana                                                                                                                    |   16397 |
|    3 | Rattus norvegicus                                                                                                                       |    8219 |
|    4 | Saccharomyces cerevisiae (strain ATCC 204508 / S288c)                                                                                   |    6733 |
|    5 | Bos taurus                                                                                                                              |    6052 |
|    6 | Schizosaccharomyces pombe (strain 972 / ATCC 24843)                                                                                     |    5123 |
|    7 | Escherichia coli (strain K12)                                                                                                           |    4531 |
|    8 | Caenorhabditis elegans                                                                                                                  |    4493 |
|    9 | Oryza sativa subsp. japonica                                                                                                            |    4195 |
|   10 | Bacillus subtilis (strain 168)                                                                                                          |    4191 |
|   11 | Dictyostelium discoideum                                                                                                                |    4160 |
|   12 | Drosophila melanogaster                                                                                                                 |    3846 |
|   13 | Xenopus laevis                                                                                                                          |    3510 |
|   14 | Danio rerio                                                                                                                             |    3355 |
|   15 | Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv)                                                                                  |    2331 |
|   16 | Gallus gallus                                                                                                                           |    2312 |
|   17 | Pongo abelii                                                                                                                            |    2218 |
|   18 | Salmonella typhimurium (strain LT2 / SGSC1412 / ATCC 700720)                                                                            |    1830 |
|   19 | Methanocaldococcus jannaschii (strain ATCC 43067 / DSM 2661 / JAL-1 / JCM 10045 / NBRC 100440)                                          |    1787 |
|   20 | Xenopus tropicalis                                                                                                                      |    1713 |
|   21 | Pseudomonas aeruginosa (strain ATCC 15692 / DSM 22644 / CIP 104116 / JCM 14847 / LMG 12228 / 1C / PRS 101 / PAO1)                       |    1479 |
|   22 | Sus scrofa                                                                                                                              |    1459 |
|   23 | Macaca fascicularis                                                                                                                     |    1176 |
|   24 | Candida albicans (strain SC5314 / ATCC MYA-2876)                                                                                        |    1147 |
|   25 | Emericella nidulans (strain FGSC A4 / ATCC 38163 / CBS 112.46 / NRRL 194 / M139)                                                        |    1026 |
|   26 | Oryctolagus cuniculus                                                                                                                   |     979 |
|   27 | Neurospora crassa (strain ATCC 24698 / 74-OR23-1A / CBS 708.71 / DSM 1257 / FGSC 987)                                                   |     970 |
|   28 | Aspergillus fumigatus (strain ATCC MYA-4609 / CBS 101355 / FGSC A1100 / Af293)                                                          |     949 |
|   29 | Eremothecium gossypii (strain ATCC 10895 / CBS 109.51 / FGSC 9923 / NRRL Y-1056)                                                        |     928 |
|   30 | Kluyveromyces lactis (strain ATCC 8585 / CBS 2359 / DSM 70799 / NBRC 1267 / NRRL Y-1140 / WM37)                                         |     919 |
|   31 | Candida glabrata (strain ATCC 2001 / BCRC 20586 / JCM 3761 / NBRC 0622 / NRRL Y-65 / CBS 138)                                           |     888 |
|   32 | Salmonella choleraesuis (strain SC-B67)                                                                                                 |     882 |
|   33 | Oryza sativa subsp. indica                                                                                                              |     873 |
|   34 | Canis lupus familiaris                                                                                                                  |     854 |
|   35 | Zea mays                                                                                                                                |     850 |
|   36 | Staphylococcus aureus (strain NCTC 8325 / PS 47)                                                                                        |     812 |
|   37 | Escherichia coli (strain K12 / DH10B)                                                                                                   |     771 |
|   38 | Escherichia coli (strain K12 / MC4100 / BW2952)                                                                                         |     765 |
|   39 | Pseudomonas putida (strain ATCC 47054 / DSM 6125 / CFBP 8728 / NCIMB 11950 / KT2440)                                                    |     738 |
|   40 | Pan troglodytes                                                                                                                         |     692 |
|   41 | Pseudomonas syringae pv. tomato (strain ATCC BAA-871 / DC3000)                                                                          |     683 |
|   42 | Bacillus cereus (strain ATCC 14579 / DSM 31 / CCUG 7414 / JCM 2152 / NBRC 15305 / NCIMB 9373 / NCTC 2599 / NRRL B-3711)                 |     670 |
|   43 | Yarrowia lipolytica (strain CLIB 122 / E 150)                                                                                           |     667 |
|   44 | Debaryomyces hansenii (strain ATCC 36239 / CBS 767 / BCRC 21394 / JCM 1990 / NBRC 0083 / IGC 2968)                                      |     653 |
|   45 | Pseudomonas aeruginosa (strain UCBPP-PA14)                                                                                              |     620 |
|   46 | Helicobacter pylori (strain ATCC 700392 / 26695)                                                                                        |     613 |
|   47 | Aspergillus oryzae (strain ATCC 42149 / RIB 40)                                                                                         |     586 |
|   48 | Caenorhabditis briggsae                                                                                                                 |     582 |
|   49 | Streptococcus pneumoniae serotype 4 (strain ATCC BAA-334 / TIGR4)                                                                       |     519 |
|   50 | Solanum lycopersicum                                                                                                                    |     508 |
|   51 | Nicotiana tabacum                                                                                                                       |     506 |
|   52 | Pseudomonas aeruginosa (strain LESB58)                                                                                                  |     485 |
|   53 | Mycoplasma genitalium (strain ATCC 33530 / DSM 19775 / NCTC 10195 / G37)                                                                |     483 |
|   54 | Ovis aries                                                                                                                              |     461 |
|   55 | Aspergillus terreus (strain NIH 2624 / FGSC A1156)                                                                                      |     450 |
|   56 | Glycine max                                                                                                                             |     439 |
|   57 | Burkholderia thailandensis (strain ATCC 700388 / DSM 13276 / CCUG 48851 / CIP 106301 / E264)                                            |     434 |
|   58 | Encephalitozoon cuniculi (strain GB-M1)                                                                                                 |     424 |
|   59 | Mycosarcoma maydis                                                                                                                      |     417 |
|   60 | Saccharomyces cerevisiae (strain YJM789)                                                                                                |     414 |
|   61 | Solanum tuberosum                                                                                                                       |     408 |
|   62 | Pisum sativum                                                                                                                           |     402 |
|   63 | Gibberella zeae (strain ATCC MYA-4620 / CBS 123657 / FGSC 9075 / NRRL 31084 / PH-1)                                                     |     400 |
|   64 | Aspergillus niger (strain ATCC MYA-4892 / CBS 513.88 / FGSC A1513)                                                                      |     397 |
|   65 | Triticum aestivum                                                                                                                       |     381 |
|   66 | Cryptococcus neoformans var. neoformans serotype D (strain JEC21 / ATCC MYA-565)                                                        |     375 |
|   67 | Pyricularia oryzae (strain 70-15 / ATCC MYA-4617 / FGSC 8958)                                                                           |     373 |
|   68 | Macaca mulatta                                                                                                                          |     365 |
|   69 | Neosartorya fischeri (strain ATCC 1020 / DSM 3700 / CBS 544.65 / FGSC A1164 / JCM 1740 / NRRL 181 / WB 181)                             |     362 |
|   70 | Chlamydomonas reinhardtii                                                                                                               |     355 |
|   71 | Cryptococcus neoformans var. neoformans serotype D (strain B-3501A)                                                                     |     352 |
|   72 | Hordeum vulgare                                                                                                                         |     351 |
|   73 | Aspergillus clavatus (strain ATCC 1007 / CBS 513.65 / DSM 816 / NCTC 3887 / NRRL 1 / QM 1276 / 107)                                     |     351 |
|   74 | Drosophila pseudoobscura pseudoobscura                                                                                                  |     348 |
|   75 | Cavia porcellus                                                                                                                         |     306 |
|   76 | Plasmodium falciparum (isolate 3D7)                                                                                                     |     295 |
|   77 | Anopheles gambiae                                                                                                                       |     293 |
|   78 | Cyriopagopus hainanus                                                                                                                   |     292 |
|   79 | Equus caballus                                                                                                                          |     292 |
|   80 | Spinacia oleracea                                                                                                                       |     288 |
|   81 | Vanderwaltozyma polyspora (strain ATCC 22028 / DSM 70294 / BCRC 21397 / CBS 2163 / NBRC 10782 / NRRL Y-8283 / UCD 57-17)                |     286 |
|   82 | Aedes aegypti                                                                                                                           |     285 |
|   83 | Gorilla gorilla gorilla                                                                                                                 |     282 |
|   84 | Aspergillus fumigatus (strain CBS 144.89 / FGSC A1163 / CEA10)                                                                          |     280 |
|   85 | Mesocricetus auratus                                                                                                                    |     276 |
|   86 | Phaeosphaeria nodorum (strain SN15 / ATCC MYA-4574 / FGSC 10173)                                                                        |     269 |
|   87 | Aspergillus flavus (strain ATCC 200026 / FGSC A1120 / IAM 13836 / NRRL 3357 / JCM 12722 / SRRC 167)                                     |     266 |
|   88 | Scheffersomyces stipitis (strain ATCC 58785 / CBS 6054 / NBRC 10063 / NRRL Y-11545)                                                     |     266 |
|   89 | Cricetulus griseus                                                                                                                      |     248 |
|   90 | Meyerozyma guilliermondii (strain ATCC 6260 / CBS 566 / DSM 6381 / JCM 1539 / NBRC 10279 / NRRL Y-324)                                  |     244 |
|   91 | Bombyx mori                                                                                                                             |     241 |
|   92 | Chaetomium globosum (strain ATCC 6205 / CBS 148.51 / DSM 1962 / NBRC 6347 / NRRL 1970)                                                  |     241 |
|   93 | Pongo pygmaeus                                                                                                                          |     239 |
|   94 | Felis catus                                                                                                                             |     233 |
|   95 | Coccidioides immitis (strain RS)                                                                                                        |     225 |
|   96 | Lycosa singoriensis                                                                                                                     |     224 |
|   97 | Arthroderma benhamiae (strain ATCC MYA-4681 / CBS 112371)                                                                               |     221 |
|   98 | Drosophila virilis                                                                                                                      |     219 |
|   99 | Drosophila yakuba                                                                                                                       |     217 |
|  100 | Porphyra purpurea                                                                                                                       |     217 |
|  101 | Pyropia yezoensis                                                                                                                       |     210 |
|  102 | Oncorhynchus mykiss                                                                                                                     |     208 |
|  103 | Lodderomyces elongisporus (strain ATCC 11503 / CBS 2605 / JCM 1781 / NBRC 1676 / NRRL YB-4239)                                          |     208 |
|  104 | Drosophila simulans                                                                                                                     |     199 |
|  105 | Saccharomyces cerevisiae (strain RM11-1a)                                                                                               |     199 |
|  106 | Botryotinia fuckeliana (strain B05.10)                                                                                                  |     192 |
|  107 | Drosophila erecta                                                                                                                       |     191 |
|  108 | Vitis vinifera                                                                                                                          |     187 |
|  109 | Daucus carota                                                                                                                           |     186 |
|  110 | Trypanosoma brucei brucei                                                                                                               |     181 |
|  111 | Sorghum bicolor                                                                                                                         |     180 |
|  112 | Cyanidium caldarium                                                                                                                     |     180 |
|  113 | Takifugu rubripes                                                                                                                       |     175 |
|  114 | Drosophila sechellia                                                                                                                    |     173 |
|  115 | Sclerotinia sclerotiorum (strain ATCC 18683 / 1980 / Ss-1)                                                                              |     168 |
|  116 | Marchantia polymorpha                                                                                                                   |     164 |
|  117 | Salmo salar                                                                                                                             |     161 |
|  118 | Phaseolus vulgaris                                                                                                                      |     160 |
|  119 | Brassica napus                                                                                                                          |     159 |
|  120 | Candida albicans                                                                                                                        |     159 |
|  121 | Penicillium rubens (strain ATCC 28089 / DSM 1075 / NRRL 1951 / Wisconsin 54-1255)                                                       |     158 |
|  122 | Guillardia theta                                                                                                                        |     157 |
|  123 | Cyanophora paradoxa                                                                                                                     |     157 |